# Generated by Django 2.2 on 2023-11-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='status_tet',
            new_name='status_text',
        ),
    ]
